CREATE TABLE account (
   id INT NOT NULL,
   name VARCHAR(50) NOT NULL,
   description VARCHAR(50) NOT NULL,
   PRIMARY KEY (id) 
);

CREATE TABLE DAY (
   ID INT NOT NULL,
   ABBREVIATION VARCHAR(50) NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY (id) 
);

CREATE TABLE FOOD_GROUP (
   NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY (NAME) 
);

CREATE TABLE FOOD_ITEM (
   ID INT NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   FOOD_GROUP VARCHAR(50) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE FOOD_PORTION (
   ID INT NOT NULL,
   ITEM INT NOT NULL,
   DAY INT NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE EXERCISE_TYPE (
   TYPE_CODE VARCHAR(50) NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY (TYPE_CODE) 
);

CREATE TABLE EXERCISE (
   ID INT NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   TYPE_CODE VARCHAR(50) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE EXERCISE_SESSION (
   ID INT NOT NULL,
   EXERCISE INT NOT NULL,
   DAY INT NOT NULL,
   PRIMARY KEY (ID)
);